apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: cat-dev-pipeline
    files:
      - conf/0000-cat-dev-input.conf
      - conf/1000-cat-dev-normalization.conf
      - conf/2000-cat-dev-main-parse.conf
      - conf/6000-cat-dev-cleanup.conf
      - conf/8000-cat-dev-error-handling.conf
      - conf/9000-cat-dev-output.conf

patches:
  - target:
      kind: Logstash
      name: logstash
    patch: |-
      - op: add
        path: /spec/podTemplate/spec/volumes/-
        value: 
          name: cat-dev-pipeline
          configMap:
            name: cat-dev-pipeline
      - op: add
        path: /spec/podTemplate/spec/containers/0/volumeMounts/-
        value:
          name: cat-dev-pipeline
          mountPath: /usr/share/logstash/conf.d/cat-dev
      - op: add
        path: /spec/podTemplate/spec/initContainers/0/volumeMounts/-
        value:
          name: cat-dev-pipeline
          mountPath: /usr/share/logstash/conf.d/cat-dev
