apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: aws-waf-pipeline
    files:
      - conf/0000-aws-waf-input.conf
      - conf/1000-aws-waf-normalization.conf
      - conf/2000-aws-waf-main-parse.conf
      - conf/6000-aws-waf-cleanup.conf
      - conf/8000-aws-waf-error-handling.conf
      - conf/9000-aws-waf-output.conf

patches:
  - target:
      kind: Logstash
      name: logstash
    patch: |-
      - op: add
        path: /spec/podTemplate/spec/volumes/-
        value: 
          name: aws-waf-pipeline
          configMap:
            name: aws-waf-pipeline
      - op: add
        path: /spec/podTemplate/spec/containers/0/volumeMounts/-
        value:
          name: aws-waf-pipeline
          mountPath: /usr/share/logstash/conf.d/aws-waf
      - op: add
        path: /spec/podTemplate/spec/initContainers/0/volumeMounts/-
        value:
          name: aws-waf-pipeline
          mountPath: /usr/share/logstash/conf.d/aws-waf
