apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: nexusfw-pipeline
    files:
      - conf/0000-nexusfw-input.conf
      - conf/1000-nexusfw-normalization.conf
      - conf/2000-nexusfw-main-parse.conf
      - conf/3000-nexusfw-ecs-mapping.conf
      - conf/6000-nexusfw-cleanup.conf
      - conf/8000-nexusfw-error-handling.conf
      - conf/9000-nexusfw-output.conf

patches:
  - target:
      kind: Logstash
      name: logstash
    patch: |-
      - op: add
        path: /spec/podTemplate/spec/volumes/-
        value: 
          name: nexusfw-pipeline
          configMap:
            name: nexusfw-pipeline
      - op: add
        path: /spec/podTemplate/spec/containers/0/volumeMounts/-
        value:
          name: nexusfw-pipeline
          mountPath: /usr/share/logstash/conf.d/nexusfw
      - op: add
        path: /spec/podTemplate/spec/initContainers/0/volumeMounts/-
        value:
          name: nexusfw-pipeline
          mountPath: /usr/share/logstash/conf.d/nexusfw
