apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: vpcflow-pipeline
    files:
      - conf/0000-vpcflow-input.conf
      - conf/1000-vpcflow-normalization.conf
      - conf/2000-vpcflow-main-parse.conf
      - conf/3000-vpcflow-ecs-mapping.conf
      - conf/4000-vpcflow-enrichment.conf
      - conf/6000-vpcflow-cleanup.conf
      - conf/9000-vpcflow-output.conf

patches:
  - target:
      kind: Logstash
      name: logstash
    patch: |-
      - op: add
        path: /spec/podTemplate/spec/volumes/-
        value: 
          name: vpcflow-pipeline
          configMap:
            name: vpcflow-pipeline
      - op: add
        path: /spec/podTemplate/spec/containers/0/volumeMounts/-
        value:
          name: vpcflow-pipeline
          mountPath: /usr/share/logstash/conf.d/vpcflow
      - op: add
        path: /spec/podTemplate/spec/initContainers/0/volumeMounts/-
        value:
          name: vpcflow-pipeline
          mountPath: /usr/share/logstash/conf.d/vpcflow
