apiVersion: v1
kind: Namespace
metadata:
  name: siem
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  # labels:
    # istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: es-monitoring
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  # labels:
    # istio-injection: enabled
